import React from "react";
import TrabajosPage from "../TrabajosPage";

function BastroDeltaSound() {
  const trabajo = {
    imagenes: [
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-01.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-02.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-03.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-04.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-06.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-07.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-08.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-09.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-10.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-11.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-12.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-13.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-14.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-15.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-17.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-18.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-19.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-20.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-21.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-22.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-24.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-25.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-26.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-27.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-28.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-29.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-30.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-31.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-34.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-35.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-36.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-37.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-38.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/BASTRO DELTA SOUND/BASTRO DELTA SOUND-39.webp"
    ],
    descripcion: "Sesión fotográfica de grabación de BASTRO en Delta Sound",
    año: "2024"
  };

  return (
    <TrabajosPage
      categoria="fotografía"
      titulo="BASTRO, DELTA SOUND"
      trabajo={trabajo}
      colorHover="#bbbbbb"
      rutaVolver="/fotografia/grabaciones"
    />
  );
}

export default BastroDeltaSound;
