import React from "react";
import TrabajosPage from "../TrabajosPage";

function ViudaFederalEstudiosIon() {
  const trabajo = {
    imagenes: [
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-188.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-196.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-197.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-202.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-205.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-211.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-212.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-215.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-216.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-219.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-224.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-228.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-240.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-243.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-250.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-252.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-255.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-266.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-269.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-282.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-285.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-300.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-301.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-302.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-305.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-308.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-318.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-319.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-323.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-325.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-327.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-328.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-330.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-336.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-337.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-341.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-344.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-346.webp",
      "/trabajosimg/FOTOGRAFÍA/GRABACIÓNES/VIUDA FEDERAL ESTUDIOS ION/ION VIUDA FEDERAL-349.webp"
    ],
    descripcion: "Viuda Federal en Estudios ION, CABA. El segundo año retratando a unas de las bandas que más quiero y admiro. Gracias amigos.",
    año: "2026"
  };

  return (
    <TrabajosPage
      categoria="fotografía"
      titulo="VIUDA FEDERAL, ESTUDIOS ION"
      trabajo={trabajo}
      colorHover="#bbbbbb"
      rutaVolver="/fotografia/grabaciones"
    />
  );
}

export default ViudaFederalEstudiosIon;
